In [40]:
import pandas as pd
import numpy as np

In [41]:
ipc = pd.read_excel('C:/Users/maico/Documents/Mestrado/dmeyf2023/kaggle3/datos/ipc_arg.xlsx', header=0, index_col=0)
ipc.reset_index(inplace=True)
ipc['indice_tiempo'] = ipc['indice_tiempo'].astype(str).str.replace('-','').str[:-2].astype(int)

In [46]:
#renomear colunas para foto_mes e ipc
ipc.rename(columns={'indice_tiempo': 'foto_mes', 'ipc_nivel_general_nacional': 'ipc'}, inplace=True)

In [49]:
ipc['ipc_dif'] = ipc['ipc'].diff()

In [50]:
ipc

    foto_mes         ipc    ipc_dif
0     201901  189.610100        NaN
1     201902  196.750100   7.140000
2     201903  205.957100   9.207000
3     201904  212.959641   7.002541
4     201905  219.569100   6.609459
5     201906  225.537000   5.967900
6     201907  230.494000   4.957000
7     201908  239.607700   9.113700
8     201909  253.710200  14.102500
9     201910  262.066100   8.355900
10    201911  273.215800  11.149700
11    201912  283.444200  10.228400
12    202001  289.829900   6.385700
13    202002  295.666000   5.836100
14    202003  305.551500   9.885500
15    202004  310.124300   4.572800
16    202005  314.908700   4.784400
17    202006  321.973800   7.065100
18    202007  328.201400   6.227600
19    202008  337.063200   8.861800
20    202009  346.620700   9.557500
21    202010  359.657000  13.036300
22    202011  371.021100  11.364100
23    202012  385.882600  14.861500
24    202101  401.507100  15.624500
25    202102  415.859500  14.352400
26    202103  435.865700  20.006200
27    202104  453.650300  17.784600
28    202105  468.725000  15.074700
29    202106  483.604900  14.879900
30    202107  498.098700  14.493800
31    202108  510.394200  12.295500
32    202109  528.496800  18.102600